[buildPlans.Nexsevka]
family = "Nexsevka"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.Nexsevka.variants.design]
one = "base-flat-top-serif"
two = "curly-neck-serifless"
three = "flat-top-serifless"
four = "open-non-crossing-serifed"
five = "oblique-flat-hook-serifless"
six = "closed-contour"
seven = "straight-serifed-crossbar"
eight = "crossing"
nine = "straight-bar"
zero = "diamond-broken-reverse-slash"
capital-a = "straight-top-serifed"
capital-b = "more-asymmetric-unilateral-serifed"
capital-c = "unilateral-serifed"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-rounded-serifless-hookless"
capital-h = "top-left-bottom-right-serifed"
capital-i = "serifed"
capital-j = "descending-serifed"
capital-k = "straight-top-left-and-bottom-right-serifed"
capital-l = "motion-serifed"
capital-m = "flat-bottom-motion-serifed"
capital-n = "asymmetric-motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "detached-bend-tailed"
capital-r = "straight-open-top-left-serifed"
capital-s = "bilateral-inward-serifed"
capital-t = "motion-serifed"
capital-u = "toothed-motion-serifed"
capital-v = "straight-serifless"
capital-w = "straight-double-v-serifless"
capital-x = "straight-serifless"
capital-y = "straight-base-serifed"
capital-z = "straight-top-serifed-with-crossbar"
a = "double-storey-serifless"
b = "toothless-corner-serifed"
c = "unilateral-serifed"
d = "toothed-top-serifed"
e = "flat-crossbar"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-top-cut"
h = "straight-top-left-serifed"
i = "serifed-asymmetric"
j = "hooky"
k = "straight-top-left-serifed"
l = "zshaped"
m = "earless-single-arch-short-leg-serifless"
n = "straight-top-left-serifed"
p = "eared-motion-serifed"
q = "top-cut-straight-serifless"
r = "compact-serifed"
s = "bilateral-inward-serifed"
t = "hookless-asymmetric-short-neck2"
u = "toothless-corner-serifed"
v = "straight-motion-serifed"
w = "straight-vertical-sides-motion-serifed"
x = "straight-unilateral-motion-serifed"
y = "straight-motion-serifed"
z = "straight-top-serifed"
capital-eszet = "corner-motion-serifed"
long-s = "flat-hook-double-serifed"
eszet = "traditional-flat-hook-middle-serifed"
lower-eth = "straight-bar"
capital-thorn = "motion-serifed"
lower-thorn = "motion-serifed"
lower-alpha = "barred-top-cut-serifed"
lower-beta = "cursive"
capital-gamma = "top-right-serifed"
lower-gamma = "casual"
capital-delta = "straight"
lower-delta = "flat-top"
lower-eta = "motion-serifed"
lower-theta = "diamond"
lower-iota = "zshaped"
lower-kappa = "straight-top-left-serifed"
capital-lambda = "straight-top-serifed"
lower-lambda = "straight-turn"
lower-mu = "toothless-corner-motion-serifed"
lower-nu = "casual"
lower-xi = "flat-top"
lower-pi = "tailless"
lower-tau = "short-tailed"
lower-upsilon = "straight-serifed"
lower-phi = "straight"
lower-chi = "straight-unilateral-motion-serifed"
lower-psi = "serifed"
partial-derivative = "straight-bar"
cyrl-a = "double-storey-hook-inward-serifed-serifless"
cyrl-ve = "standard-unilateral-serifed"
cyrl-capital-zhe = "symmetric-connected"
cyrl-zhe = "symmetric-connected"
cyrl-capital-ze = "unilateral-inward-serifed"
cyrl-ze = "unilateral-inward-serifed"
cyrl-capital-ka = "symmetric-connected-top-left-and-bottom-right-serifed"
cyrl-ka = "symmetric-connected-top-left-and-bottom-right-serifed"
cyrl-el = "straight"
cyrl-em = "slanted-sides-flat-bottom-motion-serifed"
cyrl-capital-en = "top-left-bottom-right-serifed"
cyrl-en = "top-left-bottom-right-serifed"
cyrl-capital-er = "closed-motion-serifed"
cyrl-er = "eared-motion-serifed"
cyrl-capital-u = "straight-turn-motion-serifed"
cyrl-u = "straight-motion-serifed"
cyrl-ef = "top-serifed"
cyrl-che = "standard"
cyrl-yeri = "round"
cyrl-yery = "round"
cyrl-capital-e = "unilateral-inward-serifed"
cyrl-e = "unilateral-inward-serifed"
cyrl-capital-ya = "straight-open-serifless"
cyrl-ya = "straight-open-serifless"
tittle = "round"
diacritic-dot = "square"
punctuation-dot = "square"
braille-dot = "round"
tilde = "low"
asterisk = "turn-penta-low"
underscore = "above-baseline"
caret = "low"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "straight"
number-sign = "slanted-open"
ampersand = "upper-open"
at = "compact"
dollar = "slanted-interrupted-cap"
cent = "slanted-bar-interrupted-cap"
percent = "rings-segmented-slash"
bar = "force-upright"
question = "corner"
pilcrow = "curved"
micro-sign = "toothless-corner-serifed"
decorative-angle-brackets = "tall"
lig-ltgteq = "slanted"
lig-neq = "more-slanted-dotted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-plus-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.Nexsevka.variants.italic]
one = "base-flat-top-serif"
two = "curly-neck-serifless"
three = "flat-top-serifless"
four = "open-non-crossing-serifed"
five = "oblique-flat-hook-serifless"
six = "closed-contour"
seven = "straight-serifed-crossbar"
eight = "crossing"
nine = "straight-bar"
zero = "diamond-broken-reverse-slash"
capital-a = "straight-top-serifed"
capital-b = "more-asymmetric-unilateral-serifed"
capital-c = "unilateral-serifed"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-rounded-serifless-hookless"
capital-h = "top-left-bottom-right-serifed"
capital-i = "serifed"
capital-j = "descending-flat-hook-serifed"
capital-k = "straight-top-left-and-bottom-right-serifed"
capital-l = "motion-serifed"
capital-m = "flat-bottom-motion-serifed"
capital-n = "asymmetric-motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "detached-bend-tailed"
capital-r = "straight-open-top-left-serifed"
capital-s = "bilateral-inward-serifed"
capital-t = "motion-serifed"
capital-u = "toothed-motion-serifed"
capital-v = "straight-serifless"
capital-w = "straight-double-v-serifless"
capital-x = "straight-serifless"
capital-y = "straight-base-serifed"
capital-z = "straight-top-serifed-with-crossbar"
a = "single-storey-top-cut-tailed"
b = "toothless-corner-serifed"
c = "unilateral-serifed"
d = "tailed-serifed"
e = "rounded"
f = "flat-hook-extended"
g = "single-storey-flat-hook-top-cut"
h = "tailed-motion-serifed"
i = "serifed-semi-tailed"
j = "flat-hook-serifed"
k = "cursive-top-left-and-bottom-right-serifed"
l = "serifed-semi-tailed"
m = "earless-single-arch-short-leg-tailed-serifless"
n = "tailed-motion-serifed"
p = "eared-motion-serifed"
q = "top-cut-tailed-serifless"
r = "compact-top-serifed"
s = "bilateral-inward-serifed"
t = "flat-hook-asymmetric-short-neck2"
u = "toothless-corner-serifed"
v = "curly-motion-serifed"
w = "cursive-serifed"
x = "semi-chancery-curly-serifless"
y = "cursive-flat-hook-serifed"
z = "cursive"
capital-eszet = "corner-motion-serifed"
long-s = "flat-hook-descending-middle-serifed"
eszet = "traditional-flat-hook-middle-serifed"
lower-eth = "curly-bar"
capital-thorn = "motion-serifed"
lower-thorn = "motion-serifed"
lower-alpha = "crossing"
lower-beta = "standard"
capital-gamma = "top-right-serifed"
lower-gamma = "casual"
capital-delta = "straight"
lower-delta = "rounded"
lower-eta = "motion-serifed"
lower-theta = "cursive"
lower-iota = "serifed-semi-tailed"
lower-kappa = "symmetric-touching-top-left-and-bottom-right-serifed"
capital-lambda = "straight-top-serifed"
lower-lambda = "curly-tailed-turn"
lower-mu = "tailed-serifed"
lower-nu = "casual"
lower-xi = "rounded"
lower-pi = "tailed"
lower-tau = "semi-tailed"
lower-upsilon = "straight-serifed"
lower-phi = "cursive"
lower-chi = "semi-chancery-curly-serifless"
lower-psi = "serifed"
partial-derivative = "curly-bar"
cyrl-a = "single-storey-top-cut-tailed"
cyrl-ve = "cursive"
cyrl-capital-zhe = "symmetric-connected"
cyrl-zhe = "cursive"
cyrl-capital-ze = "unilateral-inward-serifed"
cyrl-ze = "unilateral-inward-serifed"
cyrl-capital-ka = "symmetric-connected-top-left-serifed"
cyrl-ka = "symmetric-connected-top-left-and-bottom-right-serifed"
cyrl-el = "tailed"
cyrl-em = "slanted-sides-flat-bottom-motion-serifed"
cyrl-capital-en = "top-left-bottom-right-serifed"
cyrl-en = "tailed-top-left-serifed"
cyrl-capital-er = "closed-motion-serifed"
cyrl-er = "eared-motion-serifed"
cyrl-capital-u = "straight-turn-motion-serifed"
cyrl-u = "cursive-flat-hook-serifed"
cyrl-ef = "cursive"
cyrl-che = "tailed"
cyrl-yeri = "round"
cyrl-yery = "round-tailed"
cyrl-capital-e = "unilateral-inward-serifed"
cyrl-e = "unilateral-inward-serifed"
cyrl-capital-ya = "straight-open-serifless"
cyrl-ya = "straight-open-tailed-serifless"
tittle = "round"
diacritic-dot = "square"
punctuation-dot = "square"
braille-dot = "round"
tilde = "low"
asterisk = "turn-penta-low"
underscore = "above-baseline"
caret = "low"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "straight"
number-sign = "slanted-open"
ampersand = "upper-open"
at = "compact"
dollar = "slanted-interrupted-cap"
cent = "slanted-bar-interrupted-cap"
percent = "rings-segmented-slash"
bar = "force-upright"
question = "corner"
pilcrow = "curved"
micro-sign = "tailed-serifed"
decorative-angle-brackets = "tall"
lig-ltgteq = "slanted"
lig-neq = "more-slanted-dotted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-plus-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.Nexsevka.ligations]
inherits = "dlig"

[buildPlans.Nexsevka.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Nexsevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Nexsevka.slopes.Italic]
angle = 11.8
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.Nexsevka.metricOverride]
xHeight = 520
cap = 690
ascender = 740
sb = 85 # Perfect

accentWidth = 182
accentClearance = 76
accentHeight = 162
accentStackOffset = 208

leading = 1250
parenSize = 860
dotSize = 'blend(weight, [100, 110], [400, 125], [900, 150])'
periodSize = 140

essRatio = 1.03
essRatioUpper = 1.03
essRatioLower = 1.03
essRatioQuestion = 1.03
archDepth = 152
smallArchDepth = 157